#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR
git update-index -q --refresh
if ! git diff-index --quiet HEAD --; then
  echo "Updating the script"
  git pull
fi
