#!/bin/bash
if [ -z $GH_USER ]; then
  echo -e "Github username ?"
  read github_user
  export GH_USER=$github_user
  echo "export GH_USER=$github_user" >>~/.bashrc
fi
if [ -z $GH_TOKEN ]; then
  echo -e "You'll need an access to the github API\n"
  echo -e "Go to this url, check all the boxes"
  echo "Check the first box, hit 'Generate token' and copy the token"
  echo -e "https://github.com/settings/tokens/new?description=retinens-scripts"
  echo -e "Github access token ?"
  read github_token
  export GH_TOKEN=$github_token
  echo "export GH_TOKEN=$github_token" >>~/.bashrc
fi
