#!/bin/bash
RETINENS_SCRIPTS_FOLDER=$(cd $(dirname $0) && pwd)

$RETINENS_SCRIPTS_FOLDER/check-updates

echo -e "\e[32m
  _____  ______ _______ _____ _   _ ______ _   _  _____
 |  __ \|  ____|__   __|_   _| \ | |  ____| \ | |/ ____|
 | |__) | |__     | |    | | |  \| | |__  |  \| | (___
 |  _  /|  __|    | |    | | | . \` |  __| | . \` |\___ \\
 | | \ \| |____   | |   _| |_| |\  | |____| |\  |____) |
 |_|  \_\______|  |_|  |_____|_| \_|______|_| \_|_____/
\e[0m"

#project name
echo -e "Project name ?"
read projectname

cd "$projectname" || exit

git add .
git commit -m "wip"
git pull
git add .
git commit -m "wip"
git push
exit