#!/bin/bash
RETINENS_SCRIPTS_FOLDER=$(cd $(dirname $0) && pwd)

projectname=ergyvet

#check if directory exists
if [ -d "$projectname" ]; then
  echo -e "\e[31mERROR \e[0m: $projectname directory already exists."
  exit
fi

reponame=retinens/"$projectname"
gh repo clone "$reponame";
exit

