#!/bin/bash -i
RETINENS_SCRIPTS_FOLDER=$(cd $(dirname $0) && pwd)

$RETINENS_SCRIPTS_FOLDER/check-updates

echo -e "\e[33m
██████  ███████ ████████ ██ ███    ██ ███████ ███    ██ ███████ 
██   ██ ██         ██    ██ ████   ██ ██      ████   ██ ██      
██████  █████      ██    ██ ██ ██  ██ █████   ██ ██  ██ ███████ 
██   ██ ██         ██    ██ ██  ██ ██ ██      ██  ██ ██      ██ 
██   ██ ███████    ██    ██ ██   ████ ███████ ██   ████ ███████
\e[0m"

#project name
echo -e "New \e[33mLaravel\e[0m project script\n"
echo -e "Project name ?"
read projectname


cd "$projectname" || exit

echo -e "Getting \e[32mbasic libraries\e[0m for Laravel (SEOTools & laravel-cookie-consent)"
composer require artesaos/seotools spatie/laravel-cookie-consent --quiet
php artisan vendor:publish --provider="Artesaos\SEOTools\Providers\SEOToolsServiceProvider" --quiet

echo -e "Installing \e[32mLaravel UI\e[0m & \e[32mBootstrap \e[0m"
composer require laravel/ui --quiet
php artisan ui bootstrap --quiet

echo -e "<?php

Route::get('/', function () {
    return view('app.pages.home');
})->name('home');" > routes/web.php

echo -e "Setting up \e[32msass\e[0m boilerplate"
mkdir resources/app
mv resources/js resources/app
rm resources/sass -rf
#getting sass boilerplate
git clone --depth=1 git://github.com/retinens/laravel-sass-boilerplate resources/app/sass --quiet && rm resources/app/sass/.git -rf

echo -e "Setting up \e[32mviews\e[0m boilerplate"

rm resources/views -rf
#getting views boiler plate
git clone --depth=1 git://github.com/retinens/laravel-views-boilerplate resources/views --quiet && rm resources/views/.git -rf

echo -e "Editing\e[32m webpack.mix.js\e[0m to work with our boilerplate and setting up \e[32mbrowser-sync\e[0m"

echo "
const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

const domain = '$projectname.test'; 
const homedir = require('os').homedir();
mix.browserSync({
    proxy: 'https://' + domain,
    host: domain,
    open: 'external',
    https: {
        key: homedir + '/.valet/Certificates/' + domain + '.key',
        cert: homedir + '/.valet/Certificates/' + domain + '.crt',
    },
});

mix.js('resources/app/js/app.js', 'public/app/js').extract().mergeManifest();
    mix.sass('resources/app/sass/app.scss', 'public/app/css');" >webpack.mix.js

echo -e "Compiling assets"
npm add laravel-mix-merge-manifest vue-template-compiler browser-sync browser-sync-webpack-plugin --save
npm install
npm run dev
npm run dev

echo -e "Setting up git repo"

git init
git flow init -d
echo "/.idea" >>.gitignore
git add .
git commit -m "First commit" --quiet

echo -e "\e[32mCreating now a repository on github\e[0m"

gh repo create retinens/"$projectname" -y --private
git push origin develop --set-upstream
echo -e "Setting up valet"
valet secure
valet open
exit
