#!/bin/bash -i
echo "admin name:"
read nameAdmin

echo "email of the admin account ;"
read emailAdmin

echo "admin password:"
read -s passwordAdmin

echo "
<?php

use App\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        User::create([
            'email' => '$emailAdmin',
            'name' => '$nameAdmin',
            'password' => bcrypt('$passwordAdmin'),
            'type' => 'admin'
        ]);
    }
}" > database/seeds/DatabaseSeeder.php

php artisan migrate:fresh --seed  --quiet