#!/bin/bash -i
RETINENS_SCRIPTS_FOLDER=$(cd $(dirname $0) && pwd)

$RETINENS_SCRIPTS_FOLDER/check-updates
source $RETINENS_SCRIPTS_FOLDER/dotenv

echo -e "\e[33m
  _____  ______ _______ _____ _   _ ______ _   _  _____
 |  __ \|  ____|__   __|_   _| \ | |  ____| \ | |/ ____|
 | |__) | |__     | |    | | |  \| | |__  |  \| | (___
 |  _  /|  __|    | |    | | | . \` |  __| | . \` |\___ \\
 | | \ \| |____   | |   _| |_| |\  | |____| |\  |____) |
 |_|  \_\______|  |_|  |_____|_| \_|______|_| \_|_____/
\e[0m"

#project name
echo -e "Cloning \e[33mLaravel\e[0m project script\n"
echo -e "Project name (from Github) ?"
read projectname

#check if directory exists
if [ -d "$projectname" ]; then
  echo -e "\e[31mERROR \e[0m: $projectname directory already exists."
  exit
fi

gh repo clone retinens/"$projectname" > /dev/null

cd "$projectname" || exit
git flow init -d
composer install --quiet

cp .env.example .env

php artisan key:generate --quiet
#php artisan migrate:fresh --seed
npm install -s --no-warnings

valet db:create "$projectname"

echo -e "Setting up your .env file"

.env set MAIL_HOST="0.0.0.0"
.env set MAIL_PORT="1025"
.env set MAIL_FROM="test@"$projectname.".test"
.env set DB_DATABASE="$projectname"
.env set DB_USERNAME="root"
.env set DB_PASSWORD="root"
.env set APP_URL="https://"$projectname".test"


echo -e "Setting up valet"
valet secure
#php artisan migrate:fresh --seed


exit
